export interface ColorPalette {
  id: string;
  name: string;
  emoji: string;
  primary: string;
  secondary: string;
  accent: string;
  description: string;
}

export const colorPalettes: ColorPalette[] = [
  {
    id: 'lime-punch',
    name: 'Lime Punch',
    emoji: '🍋',
    primary: '#84cc16',
    secondary: '#eab308',
    accent: '#22c55e',
    description: 'Energetic & Fresh',
  },
  {
    id: 'blue-spectrum',
    name: 'Blue Spectrum',
    emoji: '💙',
    primary: '#3b82f6',
    secondary: '#06b6d4',
    accent: '#8b5cf6',
    description: 'Professional & Modern',
  },
  {
    id: 'emerald-forest',
    name: 'Emerald Forest',
    emoji: '🌲',
    primary: '#10b981',
    secondary: '#14b8a6',
    accent: '#06b6d4',
    description: 'Fresh & Innovative',
  },
  {
    id: 'sunset-glow',
    name: 'Sunset Glow',
    emoji: '🌅',
    primary: '#f59e0b',
    secondary: '#ec4899',
    accent: '#8b5cf6',
    description: 'Bold & Creative',
  },
  {
    id: 'electric-purple',
    name: 'Electric Purple',
    emoji: '⚡',
    primary: '#a855f7',
    secondary: '#ec4899',
    accent: '#3b82f6',
    description: 'Futuristic & Modern',
  },
  {
    id: 'crimson-tech',
    name: 'Crimson Tech',
    emoji: '🔴',
    primary: '#ef4444',
    secondary: '#f97316',
    accent: '#ec4899',
    description: 'Powerful & Bold',
  },
  {
    id: 'ocean-deep',
    name: 'Ocean Deep',
    emoji: '🌊',
    primary: '#0ea5e9',
    secondary: '#06b6d4',
    accent: '#8b5cf6',
    description: 'Professional & Calm',
  },
  {
    id: 'mint-fresh',
    name: 'Mint Fresh',
    emoji: '🌿',
    primary: '#22c55e',
    secondary: '#10b981',
    accent: '#06b6d4',
    description: 'Clean & Modern',
  },
  {
    id: 'royal-gold',
    name: 'Royal Gold',
    emoji: '👑',
    primary: '#f59e0b',
    secondary: '#eab308',
    accent: '#f97316',
    description: 'Luxury & Premium',
  },
  {
    id: 'neon-synthwave',
    name: 'Neon Synthwave',
    emoji: '🎮',
    primary: '#ec4899',
    secondary: '#8b5cf6',
    accent: '#06b6d4',
    description: 'Retro Futuristic',
  },
  {
    id: 'arctic-blue',
    name: 'Arctic Blue',
    emoji: '❄️',
    primary: '#06b6d4',
    secondary: '#0ea5e9',
    accent: '#7dd3fc',
    description: 'Cool & Tech',
  },
  {
    id: 'monochrome',
    name: 'Monochrome',
    emoji: '⚫',
    primary: '#000000',
    secondary: '#404040',
    accent: '#737373',
    description: 'Pure Brutalist',
  },
  {
    id: 'coral-reef',
    name: 'Coral Reef',
    emoji: '🪸',
    primary: '#fb7185',
    secondary: '#f472b6',
    accent: '#fbbf24',
    description: 'Vibrant & Warm',
  },
  {
    id: 'indigo-nights',
    name: 'Indigo Nights',
    emoji: '🌌',
    primary: '#6366f1',
    secondary: '#8b5cf6',
    accent: '#a855f7',
    description: 'Deep & Mystical',
  },
  {
    id: 'fire-orange',
    name: 'Fire Orange',
    emoji: '🔥',
    primary: '#f97316',
    secondary: '#fb923c',
    accent: '#fdba74',
    description: 'Hot & Dynamic',
  },
  {
    id: 'slate-professional',
    name: 'Slate Pro',
    emoji: '💼',
    primary: '#64748b',
    secondary: '#475569',
    accent: '#334155',
    description: 'Corporate & Serious',
  },
  {
    id: 'bubblegum-pop',
    name: 'Bubblegum Pop',
    emoji: '🍬',
    primary: '#f472b6',
    secondary: '#ec4899',
    accent: '#a855f7',
    description: 'Playful & Fun',
  },
  {
    id: 'forest-moss',
    name: 'Forest Moss',
    emoji: '🍃',
    primary: '#65a30d',
    secondary: '#84cc16',
    accent: '#059669',
    description: 'Natural & Earthy',
  },
  {
    id: 'navy-command',
    name: 'Navy Command',
    emoji: '⚓',
    primary: '#1e40af',
    secondary: '#1e3a8a',
    accent: '#3730a3',
    description: 'Strong & Reliable',
  },
  {
    id: 'cherry-blossom',
    name: 'Cherry Blossom',
    emoji: '🌸',
    primary: '#fda4af',
    secondary: '#f9a8d4',
    accent: '#c084fc',
    description: 'Soft & Elegant',
  },
];

export const getColorPalette = (id: string): ColorPalette => {
  return colorPalettes.find((palette) => palette.id === id) || colorPalettes[0];
};
